
  CREATE TABLE "DBUSERNEB"."COMPANY" 
   (	"COMPANY_KEY" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANY_UID" VARCHAR2(64 BYTE), 
	"UID_DUP" VARCHAR2(1 BYTE), 
	"STATUS" NUMBER(1,0), 
	"COMPANY_KIND" NUMBER(2,0), 
	"COMPANY_BU_TYPE" NUMBER(1,0), 
	"COMPANY_NAME" NVARCHAR2(256), 
	"COMPANY_ENAME" VARCHAR2(256 BYTE), 
	"UAA_LEVEL" NUMBER(1,0), 
	"DEFAULT_FLOW_SCHEMA_KEY" NUMBER(9,0), 
	"SCHEMA_SUIT_OPERATOR_KEY" NUMBER(9,0), 
	"SCHEMA_SUIT_CREATE_TIME" TIMESTAMP (6), 
	"ESTABLISH_DATE" DATE, 
	"DEFAULT_BRANCH_ID" VARCHAR2(4 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"FAX" VARCHAR2(16 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"EMAILS" VARCHAR2(256 BYTE), 
	"RETRY_FLAG" NUMBER(1,0), 
	"LOGIN_FLAG" NUMBER(1,0), 
	"SALARY_FLAG" NUMBER(1,0), 
	"ONLINE_PAYEE_FLAG" NUMBER(1,0), 
	"ROOT1_TX_FLAG" NUMBER(1,0), 
	"ROOT2_TX_FLAG" NUMBER(1,0), 
	"PAYER_ACCOUNT_FLAG" NUMBER(1,0), 
	"PAYEE_ACCOUNT_FLAG" NUMBER(1,0), 
	"FAX_FLAG" NUMBER(1,0), 
	"TW_ATM_FLAG" NUMBER(1,0), 
	"TW_REMIT_FLAG" NUMBER(1,0), 
	"TW_FXML_FLAG" NUMBER(1,0), 
	"TW_PAYEE_FLAG" NUMBER(1,0), 
	"TW_AMT_QUOTA" NUMBER(15,2), 
	"TW_INTER_REMIT_QUOTA" NUMBER(15,2), 
	"REGISTER_TIME" TIMESTAMP (6), 
	"CANCEL_TIME" TIMESTAMP (6), 
	"LAST_BRANCH_ID" VARCHAR2(4 BYTE), 
	"LAST_EDITOR_KEY" NUMBER(9,0), 
	"LAST_MANAGER_KEY" NUMBER(9,0), 
	"LAST_UPDATE_TIME" TIMESTAMP (6), 
	"QUERY_ONLY_FLAG" NUMBER(1,0), 
	"KYC_REVALIDATED" NUMBER(1,0), 
	"KYC_REVALIDATED_DATE" TIMESTAMP (6), 
	"MASS_CHECK" VARCHAR2(2 BYTE), 
	"CUSTOM_AUDIT_ID" VARCHAR2(32 BYTE), 
	"UPDATE_DAY" DATE DEFAULT to_date('20240929','yyyymmdd')
   ) 
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_KEY" IS '公司鍵值
IDENTITY';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_UID" IS '公司統編
登入的統編或身份證字號
註銷時：加上三碼註銷碼（NN_：NN表示客戶第幾次注銷）';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."UID_DUP" IS '誤別碼';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."STATUS" IS '公司狀態
1：正常
0：暫停
-1：註銷
-2：虛擬公司（未申請網銀的關係戶）';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_KIND" IS '公司類型
1: 企業戶
2: 個人戶';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_BU_TYPE" IS '公司BU類型
1：DBU
2：OBU
-9 : 未知 (需發電文 EB12020004 取得)';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_NAME" IS '公司戶名';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."COMPANY_ENAME" IS '公司英文名稱';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."UAA_LEVEL" IS '申請的授權中心類別
0：無授權中心功能
1：單層授權
2：兩層式授權';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."DEFAULT_FLOW_SCHEMA_KEY" IS '公司預設流程鍵值
FLOW_SCHEMA.FLOWSCHEMA_KEY
0：無預設流程';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."SCHEMA_SUIT_OPERATOR_KEY" IS '流程套餐設定人員鍵值
0：尚未設定流程套餐(default)';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."SCHEMA_SUIT_CREATE_TIME" IS '流程套餐設定時間';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."ESTABLISH_DATE" IS '公司創立日期或個人出生日期';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."DEFAULT_BRANCH_ID" IS '往來分行代碼';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TEL" IS '聯絡電話';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."FAX" IS '傳真電話';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."MOBILE" IS '行動電話';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."EMAILS" IS 'Email Address
(以分號;分隔多筆)';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."RETRY_FLAG" IS '啟用餘額不足重試扣款
0：否
1：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."LOGIN_FLAG" IS '是否啟用雙重登入認證
0：否
1：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."SALARY_FLAG" IS '是否啟用電子薪資單服務
0：否
1：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."ONLINE_PAYEE_FLAG" IS '是否啟用線上約定收款人
0：否
2：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."ROOT1_TX_FLAG" IS '授權管理者是否兼具交易權限
0：否
3：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."ROOT2_TX_FLAG" IS '授權主管是否兼具交易權限
0：否
4：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."PAYER_ACCOUNT_FLAG" IS '所有存款（歸戶）帳號均視為約定轉出帳號（包含未來新開立的帳號）
0：否
5：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."PAYEE_ACCOUNT_FLAG" IS '所有轉出帳號均視為約定轉入帳號（包含未來新約定的轉出帳號）
0：否
6：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."FAX_FLAG" IS '否啟用傳真服務
0：否
7：是';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_ATM_FLAG" IS '是否啟用ATM轉帳';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_REMIT_FLAG" IS '是否啟用通匯轉帳';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_FXML_FLAG" IS '是否啟用FXML轉帳';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_PAYEE_FLAG" IS '轉入帳號是否限常用收款人';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_AMT_QUOTA" IS 'ATM付款金額上限（元）';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."TW_INTER_REMIT_QUOTA" IS '跨行通匯付款金額上限（元）';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."REGISTER_TIME" IS '申請時間';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."CANCEL_TIME" IS '網銀帳戶註銷時間';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."LAST_BRANCH_ID" IS '最後更新分行代碼';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."LAST_EDITOR_KEY" IS '最後更新經辦鍵值';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."LAST_MANAGER_KEY" IS '最後更新主管鍵值';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."LAST_UPDATE_TIME" IS '最後異動時間';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."QUERY_ONLY_FLAG" IS '申請功能限查詢
1：不能勾選申辦業務子系統';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."KYC_REVALIDATED" IS '是否已重做KYC';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."KYC_REVALIDATED_DATE" IS 'KYC重做時間';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."MASS_CHECK" IS 'TFB 客群代碼';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."CUSTOM_AUDIT_ID" IS '交易被授權人身分證字號';
   COMMENT ON COLUMN "DBUSERNEB"."COMPANY"."UPDATE_DAY" IS '系統時間';
   COMMENT ON TABLE "DBUSERNEB"."COMPANY"  IS '公司基本資料';


--近三個月使用兩種身分登入會員客戶ID(不重複)  
SELECT DISTINCT
    c.COMPANY_KEY,
    c.COMPANY_UID,
    DBUSERNEB.get_dec_val(c.COMPANY_UID,'4E455742616E6B696E67323031343130') as id,
    c.COMPANY_KIND
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        DBUSERNEB.COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN (1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN (3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (1, 2, 3, 4)
    -- 確認用戶有使用企業/個人戶身份登入
    AND EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c1
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l1 ON c1.COMPANY_KEY = l1.COMPANY_KEY
        WHERE c1.COMPANY_UID = c.COMPANY_UID
        AND c1.COMPANY_KIND IN (1, 2)
        AND l1.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
    -- 確認用戶有使用信用卡身份登入
    AND EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c2
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l2 ON c2.COMPANY_KEY = l2.COMPANY_KEY
        WHERE c2.COMPANY_UID = c.COMPANY_UID
        AND c2.COMPANY_KIND IN (3, 4)
        AND l2.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;

--近三個月僅使用信用卡會員身分登入ID(不重複)
SELECT DISTINCT
    c.COMPANY_UID,
    DBUSERNEB.get_dec_val(c.COMPANY_UID,'4E455742616E6B696E67323031343130') as id,
    c.COMPANY_KIND
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        DBUSERNEB.COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN (1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN (3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (3, 4)
    -- 確認用戶有使用信用卡身份登入
    AND EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c1
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l1 ON c1.COMPANY_KEY = l1.COMPANY_KEY
        WHERE c1.COMPANY_UID = c.COMPANY_UID
        AND c1.COMPANY_KIND IN (3, 4)
        AND l1.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
    -- 確認用戶沒有使用企業/個人戶身份登入
    AND NOT EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c2
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l2 ON c2.COMPANY_KEY = l2.COMPANY_KEY
        WHERE c2.COMPANY_UID = c.COMPANY_UID
        AND c2.COMPANY_KIND IN (1, 2)
        AND l2.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;


-- 近六個月未登入Fubon+ & 為信用卡會員客戶ID(不重複)-->
SELECT DISTINCT
 count(c.COMPANY_KEY) as count
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        DBUSERNEB.COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN (1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN (3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (3, 4)
    -- 確認用戶近六個月未通過 Fubon+ 登入
    AND NOT EXISTS (
        SELECT 1
        FROM DBUSERNEB.EB_LOGIN_LOG_B l
        WHERE l.COMPANY_KEY = c.COMPANY_KEY
        AND l.CHANNEL_ID = 'M'  -- Fubon+ 通路
        AND l.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -6)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;


create or replace FUNCTION           get_dec_val( 
    p_in_hex  IN VARCHAR2, 
    p_key_hex IN VARCHAR2 ) 
  RETURN VARCHAR2 
IS 
  l_ret VARCHAR2 (2000); 
  l_dec_val raw (2000); 
  p_in raw(2000); 
  p_key raw(2000); 
  l_mod NUMBER := dbms_crypto.ENCRYPT_AES128 + dbms_crypto.CHAIN_ECB + dbms_crypto.PAD_PKCS5; 
BEGIN 
  p_in      := hextoraw(p_in_hex); 
  p_key     := hextoraw(p_key_hex); 
  l_dec_val := dbms_crypto.decrypt ( p_in, l_mod, p_key ); 
  l_ret     := UTL_I18N.RAW_TO_CHAR(l_dec_val, 'AL32UTF8'); 
  RETURN l_ret;

-- 優化後的查詢：查找近六個月未登入Fubon+的信用卡會員客戶
-- 確保一個人只計算一次，即使他們有多個COMPANY_KIND


-- 版本2：返回詳細客戶列表
SELECT 
    base.COMPANY_UID,
    DBUSERNEB.get_dec_val(base.COMPANY_UID, '4E455742616E6B696E67323031343130') as id,
    MIN(base.COMPANY_KIND) as COMPANY_KIND  -- 只取一個COMPANY_KIND，避免重複
FROM DBUSERNEB.COMPANY base
WHERE 
    -- 條件1：此記錄是信用卡會員帳戶
    base.COMPANY_KIND IN (3, 4)
    
    -- 條件2：確認此人同時擁有企業/個人帳戶
    AND EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c2
        WHERE c2.COMPANY_UID = base.COMPANY_UID
        AND c2.COMPANY_KIND IN (1, 2)  -- 企業/個人帳戶類型
    )
    
    -- 條件3：檢查此人的所有帳戶都未在過去六個月內透過Fubon+登入
    AND NOT EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c3
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l ON l.COMPANY_KEY = c3.COMPANY_KEY
        WHERE 
            c3.COMPANY_UID = base.COMPANY_UID
            AND l.CHANNEL_ID = 'M'  -- Fubon+通路
            AND l.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -6)
    )
GROUP BY base.COMPANY_UID  -- 根據UID分組，確保每人只計算一次
ORDER BY base.COMPANY_UID;


SNAP_DATE	ACCESS_DATE	ACCESS_HHMMSS	TIMESTAMP	APPVERSION	CHANNELID	CLIENTIP	CLIENTPORT	CUSTID	DEVICEID	FLB_KEY	FROMPAGE	LANGUAGETAG	LOCALE	PAGEID	PODNAME	PROJECT_APPLICATION_NAME	PROJECT_NAME	SEED	SESSIONID	SPANID	TRACEID	TRACKINGID	DATA_APPVERSION	BUSTYPE	COMPANYKEY	COMPANYKIND	DEVICEPLATFORM	DEVICEPLATFORMVERSION	ENCCUSTID	ERRORCODE	ERRORDESC	ERRORSYSTEMID	FUNCTYPE	MASKUSERID	MASSCHK	MODEL	NAMECODE	NETWORK	RESULTCODE	RESVERSION	SERVERNAME	TASKID	USERKEY	TRANS_SN	EXEC_DATE
03/31/2025 00:00:00	03/31/2025 00:00:00	00:08:47.075	03/31/2025 00:08:47	1.1.4-20250327160116	AIBANK_APP	7.238.143.151	38933	F226691714	DD465286-AFA0-4F5B-B36C-B7F1F5046478		NGNOT001010	zh-TW	zh_TW	NGNOT001011	chl-general-deployment-v1-6cc48f95b9-p8gzf	aibank-general	aibank	DD465286-AFA0-4F5B-B36C-B7F1F5046478	e37fa4a0-16ce-48dc-be33-2eb32c4a2fdb	ccc0534db046b27f	64023f8982a11aa3d0a1dc76665205ec	F3B8BED3-6B5C-4078-9048-A671D299AB9A	1.1.4	GN			ios	18.3.2		0000	Success	SVC	OT			iPhone16,1		wifi	0	0	chl-general-deployment-v1-6cc48f95b9-p8gzf	NGNOT001		0AAAAAAAAAABTAWF	04/01/2025 00:00:00

