--近三個月使用兩種身分登入會員客戶ID(不重複)  
SELECT DISTINCT
    c.COMPANY_KEY,
    c.COMPANY_UID,
    c.COMPANY_KIND
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN(1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN(3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (1, 2, 3, 4)
    -- 確認用戶有使用企業/個人戶身份登入
    AND EXISTS (
        SELECT 1
        FROM COMPANY c1
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l1 ON c1.COMPANY_KEY = l1.COMPANY_KEY
        WHERE c1.COMPANY_UID = c.COMPANY_UID
        AND c1.COMPANY_KIND IN (1, 2)
        AND l1.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
    -- 確認用戶有使用信用卡身份登入
    AND EXISTS (
        SELECT 1
        FROM COMPANY c2
        JOIN EB_LOGIN_LOG_B l2 ON c2.COMPANY_KEY = l2.COMPANY_KEY
        WHERE c2.COMPANY_UID = c.COMPANY_UID
        AND c2.COMPANY_KIND IN (3, 4)
        AND l2.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;


--近三個月僅使用信用卡會員身分登入ID(不重複)
SELECT DISTINCT
    c.COMPANY_KEY,
    c.COMPANY_UID,
    c.COMPANY_KIND
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN(1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN(3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (3, 4)
    -- 確認用戶有使用信用卡身份登入
    AND EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c1
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l1 ON c1.COMPANY_KEY = l1.COMPANY_KEY
        WHERE c1.COMPANY_UID = c.COMPANY_UID
        AND c1.COMPANY_KIND IN (3, 4)
        AND l1.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
    -- 確認用戶沒有使用企業/個人戶身份登入
    AND NOT EXISTS (
        SELECT 1
        FROM DBUSERNEB.COMPANY c2
        JOIN DBUSERNEB.EB_LOGIN_LOG_B l2 ON c2.COMPANY_KEY = l2.COMPANY_KEY
        WHERE c2.COMPANY_UID = c.COMPANY_UID
        AND c2.COMPANY_KIND IN (1, 2)
        AND l2.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -3)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;


-- 近六個月未登入Fubon+ & 為信用卡會員客戶ID(不重複)-->
SELECT DISTINCT
    c.COMPANY_KEY,
    c.COMPANY_UID,
    c.COMPANY_KIND
FROM
    DBUSERNEB.COMPANY c
JOIN (
    -- 確認用戶同時擁有兩種身份
    SELECT 
        COMPANY_UID
    FROM 
        DBUSERNEB.COMPANY
    GROUP BY 
        COMPANY_UID
    HAVING 
        MAX(CASE WHEN COMPANY_KIND IN(1, 2) THEN 1 ELSE 0 END) = 1
        AND MAX(CASE WHEN COMPANY_KIND IN(3, 4) THEN 1 ELSE 0 END) = 1
) dual_users ON c.COMPANY_UID = dual_users.COMPANY_UID
WHERE 
    c.COMPANY_KIND IN (3, 4)
    -- 確認用戶近六個月未通過Fubon+登入
    AND NOT EXISTS (
        SELECT 1
        FROM DBUSERNEB.EB_LOGIN_LOG_B l
        WHERE l.COMPANY_KEY = DBUSERNEB.c.COMPANY_KEY
        AND l.CHANNEL_ID = 'M'  -- Fubon+通路
        AND l.LOGIN_TIME >= ADD_MONTHS(SYSDATE, -6)
    )
ORDER BY
    c.COMPANY_UID, c.COMPANY_KIND;
